### ISSUE TITLE
The key/message are converted into bytes in platform-dependant way

### ISSUE THREAD

**Issue by dmak** [inversoft/prime-jwt#1]
I think that the line [`HMACSigner:41`](https://github.com/inversoft/prime-jwt/blob/899a38db32673769fdddd54e133a0e2b784cd800/src/main/java/org/primeframework/jwt/hmac/HMACSigner.java#L41) should better be changed to

`this.secret = secret.getBytes(StandardCharsets.US_ASCII);`

because otherwise the same string key can interpreted differently on systems configured with different system charset (e.g. UTF-8 and UTF-16), and because of that these systems are not longer interoperable (even though they share the "same" key).

On the same reason the message would not be decoded correctly. I think for message one can use `StandardCharsets.UTF_8`.

See also [JSON Web Token Specification §7](https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-25#section-7), item 2:
> 2. Let the Message be the octets of the UTF-8 representation of the JWT Claims Set.

**Comment by robotdan** [comment]
Thanks for the catch.

It looks like I'm missing that on line 41 and 69, and some other places in the code. 
I would generally default to using `UTF-8`, and write that as `.getBytes(StandardCharsets.UTF_8)`. 

I am admittedly not a Unicode expert. Is there a reason you'd use `ASCII` instead of `UTF-8`?

**Comment by dmak** [comment]
Actually you can use UTF-8 for key as well. I just thought that normally one uses only characters with codes < 128...

**Comment by robotdan** [comment]
Great, thanks @dmak, I appreciate you pointing out this issue. These changes will be available in the next release.
