### ISSUE TITLE
The library does not check the situation if signature algorithm is defined but no signature is provided

### ISSUE THREAD

**Issue by dmak** [inversoft/prime-jwt#2]
Please doublecheck this is a valid issue. According to [JWS §4.1.1](https://tools.ietf.org/html/draft-ietf-jose-json-web-signature-41#section-4.1.1) "alg" Header Parameter MUST be present and MUST be understood and processed by implementations.

In my opinion that means that if "alg" is not "none", then signature must be present and verified. Attached 
[JwtTest.java.txt](https://github.com/inversoft/prime-jwt/files/1677222/JwtTest.java.txt) demonstrates the problem.

**Comment by robotdan** [comment]
Resolved in version 1.3.0
