### ISSUE TITLE
JWT signature validation can be bypassed in versions <= 1.3.0 

### ISSUE THREAD

**Issue by rcadob** [inversoft/prime-jwt#3]
# Summary
The **prime-jwt** implementation allows that any not-signed JWT be decoded and, therefore, validated by JWTDecoder class, even when a Verifier object is provided. This issue affects versions <= 1.3.0.

For security reasons, I'm contacting the developers by email with the necessary technical details.

# Description
When the _JWT.getDecoder().decode(String, Verifier...)_ is called, the JWT signature will be ignored due to a lack of validation in JWTDecoder. A new condition should be added in this class to prevent that any _encodedJWT_ without the signature part be decoded if exists at least 1 _verifier_ object.

**Comment by robotdan** [comment]
Hi @rcadob thank you for reporting this issue. The issue has been patched.

**Comment by robotdan** [comment]
Fixed under abb0d479389a2509f939452a6767dc424bb5e6ba
